In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris

In [8]:
iris = load_iris()

In [9]:
print("KEYS DATASETS:")
print(iris.keys())

print("\nFEATURE NAME:")
print(iris.feature_names)

print("\nTARGET NAME:")
print(iris.target_names)

KEYS DATASETS:
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

FEATURE NAME:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

TARGET NAME:
['setosa' 'versicolor' 'virginica']


In [10]:
X = iris.data
y = iris.target

print("FEATURE:", X.shape)
print("LABEL:", y.shape)

FEATURE: (150, 4)
LABEL: (150,)


In [11]:
print("\nFIRST DATA FEATURE:")
print(X[:5])

print("\nFIRST LABEL:")
print(y[:5])


FIRST DATA FEATURE:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

FIRST LABEL:
[0 0 0 0 0]


In [12]:
df = pd.DataFrame(X, columns=iris.feature_names)
df['target'] = y

print("\nDATAFRAME HEAD:")
print(df.head())


DATAFRAME HEAD:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
